spring:
  application:
    name: audit
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: your-topic-name-group
      enable-auto-commit: true
server:
  port: 8090

cassandra:
  host: 127.0.0.1
  port: 9042
  keyspace: my_keyspace
  table: user_audit
  datacenter: datacenter1

topic-to-consume-message: your-topic-name