name: Maven Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start Docker service
        run: |
          sudo systemctl start docker
          docker version
          docker info

      - name: Set Testcontainers environment variables
        run: |
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Build and test with Maven
        run: mvn clean install -Dorg.testcontainers.disableRyuk=true

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports