name: Maven Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Enable Docker daemon
        run: |
          sudo systemctl start docker
          docker info

      - name: Build and test with Maven
        run: mvn clean install
