name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Включаем поддержку Testcontainers
      - name: Enable Docker daemon for Testcontainers
        uses: testcontainers/testcontainers-gh-action@v1

      - name: Build and run tests
        run: mvn clean verify
